### ISSUE TITLE
ARM mnemonic renaming ignores the condition

### ISSUE THREAD

**Issue by gerph** [aquynh/capstone#1514] opened 2019-07-04 10:37 UTC
With the python bindings, I'm using the mnemonic renaming to change the ARM 'svc' instruction to appear with the RISC OS nomenclature 'SWI'. In my setup I have:

```
md.mnemonic_setup(capstone.arm_const.ARM_INS_SVC, "SWI")
```

However, this appears to break the condition code - it is removed from the decoded instruction.

Test code to demonstrate the issue:
```python
from capstone import *
import capstone.arm_const

CODE = b'\x05\x00\x00\x2f' # SWIHS 5

md = Cs(CS_ARCH_ARM, CS_MODE_ARM)
print("Regular:")
for i in md.disasm(CODE, 0x1000):
    print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))

print("Mnemonic renaming:")
md.mnemonic_setup(capstone.arm_const.ARM_INS_SVC, "SWI")
for i in md.disasm(CODE, 0x1000):
    print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))
```

which produces:

```
Regular:
0x1000:	svchs	#5
Mnemonic renaming:
0x1000:	SWI	#5
```

**Comment by aquynh** [comment] 2019-07-04 10:45
Which version is this?

**Comment by gerph** [comment] 2019-07-04 11:55
I was using the pip installed version on macOS. Installed just an hour or so back - sorry not near the computer to check the explicit version at the moment.

**Comment by aquynh** [comment] 2019-07-04 12:09
Can you try to install from "v4" branch, to see if the problem is fixed?

**Comment by gerph** [comment] 2019-07-04 18:20
Cloned (yay... 26k/s over train wifi!), and checked out branch v4.
I added a line to the test to print cs_version() and the results were the same:

```
cs_version() = (4, 0, 1024)
Regular:
0x1000:	svchs	#5
Mnemonic renaming:
0x1000:	SWI	#5
```

**Comment by gerph** [comment] 2019-07-04 18:39
I also tried with branch `next` in case it was relevant.

```
cs_version() = (5, 0, 1280)
Regular:
0x1000:	svchs	#5
Mnemonic renaming:
0x1000:	SWI	#5
```
So looks like it's not reporting the right thing there, either.

**Comment by aquynh** [comment] 2019-07-10 09:46
what do you mean by "break the condition code"?

**Comment by aquynh** [comment] 2019-07-10 09:47
do you mean the HS condition disappears?

**Comment by gerph** [comment] 2019-07-10 10:16
Yeah, I mean it is removed from the decoded instruction.

SVC is the instruction; HS is the condition code.
Renaming the instruction in unicorn should not change the condition code which appears on the disassembly.

**Comment by aquynh** [comment] 2019-07-10 10:19
You mean Capstone, not Unicorn :-)

Can you provide full script about this issue? I tried to reproduce this in
C, and did not see any problem.

**Comment by gerph** [comment] 2019-07-10 10:37
(lol) I'm very sorry for the confusion - I'm using capstone with unicorn, and 'cos you wrote them both and they work in very similar ways I got confused! :-(

The python script supplied in the report is what I was using to demonstrate it. I can probably write a C example when I get home, if you'd like?

**Comment by aquynh** [comment] 2019-07-10 11:24
If you turn on detail mode, you will see the code condition is still same.

Do you actually mean you want output having the mnemonic as "swihs"?

**Comment by gerph** [comment] 2019-07-10 11:53
Yes; if the disassembly shows the instruction as SWI without the HS it's not doing the same thing, and therefore is not a correct disassembly. It depends on how you expect people to use the library and what the intention of the mnemonic renaming is - I assumed it was there for cases like this where the instruction has been changed in name. Previously ARM called it SWI, but they seem to have renamed it to SVC in later documentation, changing from the way that it's implemented (SoftWare Interrupt) to its purpose (SerViCe).

Currently I work around this by not using the mnemonic renaming functionality, and instead manipulating the mnemonic myself:

```
                    if mnemonic[0:3] == 'SVC':
                        # Manually replace the mnemonic, due to bug in capstone
                        mnemonic = 'SWI' + mnemonic[3:]
```

I'd not noticed that the detail provided the condition code; maybe that would be a better way to manipulate them in my code, but I was largely trying to use the library with the functions it provided rather than post-processing the output. Not that I mind that :-)

**Comment by aquynh** [comment] 2019-07-10 15:54
fixed now in the "next" branch, please confirm.

**Comment by gerph** [comment] 2019-07-10 20:39
Confirmed working with my test. Thank you :-D

**Closed** 2019-07-10 20:39 UTC
