### ISSUE TITLE
Enable -Wall and -Werror

### ISSUE THREAD

**Issue by peace-maker** [aquynh/capstone#2162] opened 2023-09-12 19:47 UTC
I'd suggest enabling all warnings and making them errors to prevent distributions with stricter compiler defaults from failing to build capstone.

I've made the following change, but lots of the resulting errors are in generated code which might need a patch to the generator? So I'd rather leave this to someone more familiar with the codebase.
https://github.com/capstone-engine/capstone/compare/next...peace-maker:capstone:compile_wall_werror

https://github.com/capstone-engine/capstone/blob/8f0d5edbe8f5558f707d9ba572c1ee7320f4aa3b/CMakeLists.txt#L28-L32
```cmake
if (MSVC)
    add_compile_options(/W1 /WX /w14189)
    add_link_options(/WX)
else()
    add_compile_options(-Werror -Wall)
endif()
```

**Comment by Rot127** [comment] 2023-09-12 19:50
Duplicate of https://github.com/capstone-engine/capstone/issues/2113 :)

**Closed as completed** 2023-09-12 19:54 UTC
