### ISSUE TITLE
A1 opcode of MOV *AX, MOFFS instruction is presented with one operand

### ISSUE THREAD

**Issue by 10110111** [aquynh/capstone#458] opened 2015-08-14 19:23 UTC
The instructions `mov ax,moffs16`, `mov eax,moffs32`, `mov rax,moffs64` with opcode of `A1` are presented as `mov`/`movabs` instructions, but their operands reported consist of only one — the moffset. There should instead be two: one register and one moffset, as is for more general `8B` opcode.

**Comment by aquynh** [comment] 2015-08-15 00:55
please provide a full input in hexcode format for easier confirmation, not just `A1`, thanks.

**Comment by aquynh** [comment] 2015-08-15 00:57
also, it would be great if you can also confirm if the issue is also in the `next` branch, not only in `master` branch. thanks.

**Comment by 10110111** [comment] 2015-08-15 06:35
Well, `moffsXX` is just any sequence of bytes of the size needed. But as you wish: `A1 12 34 90 90 90 90 90 90` will work for all operand sizes.

In the `next` branch the problem is also present.

**Comment by aquynh** [comment] 2015-08-15 06:56
can you also provide the input for the rest 2 cases: `mov ax` & `mov rax` ? thanks

**Comment by 10110111** [comment] 2015-08-15 07:00
It's the same, just truncate the extra NOPs and use corresponding bit mode:

    A1 12 34 90 90 90 90 90 90 // 64 bit mode: mov rax, [0x9090909090903412]
    A1 12 34 90 90 // 32 bit mode: mov eax, [0x90903412]
    A1 12 34 // 16 bit mode: mov ax, [0x3412]

**Comment by aquynh** [comment] 2015-08-15 07:06
yes, it is better to have the full information here also for the record.

fixed now, please confirm. thanks.

**Comment by 10110111** [comment] 2015-08-15 07:12
Fixed for Intel syntax.

**Comment by aquynh** [comment] 2015-08-15 09:04
can you check the AT&T syntax now with the latest fix?

**Comment by 10110111** [comment] 2015-08-15 10:18
16 bit mode OK, 32 and 64 bit modes have 3 operands.

**Comment by aquynh** [comment] 2015-08-15 15:52
just pushed in one more commit for AT&T. thanks

**Comment by 10110111** [comment] 2015-08-15 16:57
Fixed for these now.

**Closed** 2015-08-16 10:22 UTC
