### ISSUE TITLE
5.0.x release suggestions

### ISSUE THREAD

**Issue by XVilka** [aquynh/capstone#2081] opened 2023-07-10 10:03 UTC
Would be nice to have fixes for these in the patch release:

## 5.0.1
- [x] https://github.com/capstone-engine/capstone/issues/2066
- [x] https://github.com/capstone-engine/capstone/pull/2080
- [x] https://github.com/capstone-engine/capstone/pull/2086
- [x] https://github.com/capstone-engine/capstone/pull/2095
- [x] https://github.com/capstone-engine/capstone/pull/2096
- [x] https://github.com/capstone-engine/capstone/pull/2097
- [x] https://github.com/capstone-engine/capstone/pull/2088
- [x] https://github.com/capstone-engine/capstone/pull/2090
- [x] https://github.com/capstone-engine/capstone/pull/2100
- [x] https://github.com/capstone-engine/capstone/pull/2108
- [x] https://github.com/capstone-engine/capstone/pull/2134

## 5.0.2
- [x] https://github.com/capstone-engine/capstone/issues/2154
- [x] https://github.com/capstone-engine/capstone/issues/2145
- [x] https://github.com/capstone-engine/capstone/issues/2144
- [x] https://github.com/capstone-engine/capstone/issues/2147
- [x] https://github.com/capstone-engine/capstone/issues/2079
- [x] https://github.com/capstone-engine/capstone/issues/2128
- [x] https://github.com/capstone-engine/capstone/issues/2025
- [x] https://github.com/capstone-engine/capstone/issues/2005
- [x] https://github.com/capstone-engine/capstone/issues/1955 (if it still happens)
- [ ] https://github.com/capstone-engine/capstone/issues/1893
- [x] https://github.com/capstone-engine/capstone/pull/2148
- [x] https://github.com/capstone-engine/capstone/issues/2153
- [ ] Publish news on http://www.capstone-engine.org/ for the 5.0.2 release

After they are fixed in the `next` branch, fixes could be cherry-picked to the `v5` branch one by one for the release.

**Comment by XVilka** [comment] 2023-07-11 04:26
There are also many [PPC regressions](https://github.com/capstone-engine/capstone/issues/2087) found by @wargio but they will be fixed in the https://github.com/capstone-engine/capstone/pull/2013 so it doesn't make sense trying to fix them in the patch release.

**Comment by XVilka** [comment] 2023-07-21 16:16
@kabeor you need to cherry-pick corresponding commits from `next` to `v5`: https://github.com/capstone-engine/capstone/tree/v5

**Comment by kabeor** [comment] 2023-07-21 16:24
Well looks like there are some misunderstood. v5 should merge something only if we are ready to release a version. so I think we needn't cherry-pick.

**Comment by XVilka** [comment] 2023-07-21 16:26
@kabeor but you already cherry-picked some of these fixes - SH and ARM VFP fix. Idea is to cherry-pick these fixes and tag 5.0.1

**Comment by kabeor** [comment] 2023-07-21 16:33
@XVilka Aha @aquynh did this. I should talk with him about this tmw😂

**Comment by XVilka** [comment] 2023-07-25 02:27
Looks like only x86 regression and deprecated modules left in this list, the rest was merged

**Comment by wargio** [comment] 2023-07-25 07:56
also the ppc regressions

**Comment by XVilka** [comment] 2023-07-25 13:47
@wargio there are way too many, not sure if it makes sense to devote time instead of investing time in auto-sync PPC

**Comment by Rot127** [comment] 2023-07-25 15:05
@kabeor Could we add a note to the `5.0.1` release, that the `v6` release will bring some big changes (possibly linking to https://github.com/capstone-engine/capstone/pull/2124)? In this case people have the chance to decide if they might want to skip v5 altogether.

**Comment by kabeor** [comment] 2023-07-26 07:17
@Rot127 ok, it's a perfect time to announce that.

**Comment by Rot127** [comment] 2023-07-26 09:48
@kabeor Great! You can link to the WIP release text [here](https://github.com/Rot127/capstone/blob/v6-release-guide/docs/cs_v6_release_guide.md) or to the PR.

**Comment by Rot127** [comment] 2023-07-26 11:50
@kabeor Could you please also a line that everyone is welcome to give early feedback regarding `v6`. The whole `auto-sync` thing still misses more eyes from the outside. And new releases have definitely more impact than issues.

**Comment by XVilka** [comment] 2023-08-04 03:21
@kabeor @aquynh I suggest to cherry-pick already existing fixes and tag 5.0.1
Not everything was fixed but some most annoying things were fixed already - the rest could land in 5.0.2 or something like that.

**Comment by XVilka** [comment] 2023-08-14 03:54
@kabeor @aquynh ping

**Comment by XVilka** [comment] 2023-08-19 12:29
@kabeor @aquynh ping

**Comment by kabeor** [comment] 2023-08-21 03:41
#2141

**Comment by XVilka** [comment] 2023-08-21 04:27
Thank you, @kabeor!

**Comment by XVilka** [comment] 2023-08-23 02:44
@kabeor looks like some assets missing from the release?

**Comment by kabeor** [comment] 2023-08-23 04:46
@XVilka I see. Reference to [Docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release): `Workflows are not triggered for the created, edited, or deleted activity types for draft releases.`. Maybe `published` field will fix this. Will test on next release.

**Comment by XVilka** [comment] 2023-08-24 00:18
@gerph added your issues here. Worth carving a quick 5.0.2 bugfix release when fixes are available.

**Comment by gerph** [comment] 2023-08-24 18:04
> @gerph added your issues here. Worth carving a quick 5.0.2 bugfix release when fixes are available.

Thanks :-)

There's no ticket for it, but it probably should apply to all the releases... a reminder to update the cs_version so that each release could be differentiated, would be good.

**Comment by Rot127** [comment] 2023-10-21 14:09
@XVilka Could you add https://github.com/capstone-engine/capstone/issues/2177 and https://github.com/capstone-engine/capstone/issues/2174 to the list?

**Comment by No-47** [comment] 2023-10-23 02:26
@XVilka 
This small problem can also be fixed issues：
#2177

**Comment by XVilka** [comment] 2024-01-21 03:24
@kabeor for 5.0.2 please cherry-pick https://github.com/capstone-engine/capstone/pull/2221 then.

**Comment by Rot127** [comment] 2024-03-20 04:34
Close this because we now track issues with milestones, see: https://github.com/capstone-engine/capstone/milestone/4

**Closed as completed by Rot127** 2024-03-20 04:34 UTC
