### ISSUE TITLE
capstone install fails with `pip install --user capstone`

### ISSUE THREAD

**Issue by zardus** [aquynh/capstone#380] opened 2015-05-29 04:33 UTC
I found this while debugging a pyvex installation info for someone:

```ShellSession
$ pip install --user capstone
Downloading/unpacking capstone
  Downloading capstone-3.0.3.tar.gz (2.4MB): 2.4MB downloaded
  Running setup.py (path:/tmp/pip_build_yans/capstone/setup.py) egg_info for package capstone
    
Installing collected packages: capstone
  Running setup.py install for capstone
    building 'capstone' library
...
running install_data

creating /usr/lib/python2.7/dist-packages/capstone

error: could not create '/usr/lib/python2.7/dist-packages/capstone': Permission denied

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_yans/capstone/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-WAWtXe-record/install-record.txt --single-version-externally-managed --compile --user failed with error code 1 in /tmp/pip_build_yans/capstone
Storing debug log for failure in /home/yans/.pip/pip.log
$
```

Installs in a virtualenv seem to work great.

**Comment by aquynh** [comment] 2015-05-29 06:31
how about "sudo pip install capstone" ?

**Comment by zardus** [comment] 2015-05-29 06:35
I'm sure that'll work, but the whole point of `pip install --user` is to install it to `$HOME/.local` and not clobber the system :-)

**Comment by aquynh** [comment] 2015-05-29 06:38
yes, if you can fix this, then a pull request is welcome.

thanks.

**Comment by zardus** [comment] 2015-05-29 06:41
I'll try to check it out after the CGC quals :-)

**Comment by aquynh** [comment] 2015-06-02 14:18
do you have any comments on this pull request: https://github.com/aquynh/capstone/pull/384 ?

**Comment by aquynh** [comment] 2015-06-04 13:57
i have merged the related pull request to solve this issue to the "master" & "next" branches.
please report if you still have issues, thanks.

**Closed by aquynh** 2015-06-04 13:57 UTC

**Comment by aquynh** [comment] 2017-05-02 23:39
You did not have permission to install? Which command did you run?

**Comment by carlorosati** [comment] 2017-05-03 01:16
Same as the title

**Comment by carlorosati** [comment] 2017-05-03 01:16
Do you want the full log?

**Comment by aquynh** [comment] 2017-05-03 01:23
you are still installing Capstone 3.0.4 from Pypi. however, i cannot reproduce it here on MacOS: the same command works without issues here.

you can try to install directly from Github with the command below:

```
pip install --user "https://github.com/aquynh/capstone/archive/next.zip#egg=capstone&subdirectory=bindings/python"
```

**Comment by carlorosati** [comment] 2017-05-03 05:14
That worked
