### ISSUE TITLE
negative byte value is expanded

### ISSUE THREAD

**Issue by radare** [aquynh/capstone#305] opened 2015-04-04 00:53 UTC
wrong negative byte value
```
$ rasm2 -d 348b
xor al, 0xffffff8b
```

should be like udis:
```
$ rasm2 -a x86.udis -d 348b
xor al, 0x8b
```

**Comment by aquynh** [comment] 2015-04-04 05:37
fixed in the *next* branch, thanks.

**Closed** 2015-04-09 16:43 UTC

**Comment by learn-more** [comment] 2015-04-22 17:42
In case someone stumbles upon this and is wondering what the cause is: sign extension.
Explained here: http://en.wikipedia.org/wiki/Sign_extension
