### ISSUE TITLE
[Bug] Regression with 83e4f0 : and esp, 0xfffffff0 -> and esp, 0xf0

### ISSUE THREAD

**Issue by Maijin** [aquynh/capstone#529] opened 2015-11-05 18:27 UTC
Next branch
Regression with 83e4f0 
-and esp, 0xfffffff0
+and esp, 0xf0

See https://travis-ci.org/radare/radare2/jobs/89478511#L632 for example

**Comment by aquynh** [comment] 2015-11-06 02:10
confirmed. this is due to a recent commit https://github.com/aquynh/capstone/pull/527. will see how to fix it, thanks.

**Comment by aquynh** [comment] 2015-11-07 09:38
i reverted that commit, so this issue should be fixed now.

**Closed** 2015-11-18 18:29 UTC
