### ISSUE TITLE
pip install on Mac

### ISSUE THREAD

**Issue by jpziegler** [aquynh/capstone#2327] opened 2024-04-23 14:00 UTC
### Work environment

| Questions                                | Answers
|------------------------------------------|--------------------
| OS/arch/bits                             | MacOS AArch64
| Architecture                             | arm64
| Source of Capstone                       | pip
| Version/git commit                       | see description

### Expected behavior
Should install arm64 version of capstone.

### Actual behavior
Installs x86 version of capstone.

Here's the error I'm seeing:
```
OSError: dlopen(/Users/xxx/.pyenv/versions/3.12.2/lib/python3.12/site-packages/capstone/lib/libcapstone.dylib, 0x0006): tried: '/Users/xxx/.pyenv/versions/3.12.2/lib/python3.12/site-packages/capstone/lib/libcapstone.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/xxx/.pyenv/versions/3.12.2/lib/python3.12/site-packages/capstone/lib/libcapstone.dylib' (no such file), '/Users/xxx/.pyenv/versions/3.12.2/lib/python3.12/site-packages/capstone/lib/libcapstone.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
```

### Steps to reproduce the behavior

I ran into this when attempting to install ROPGadget. Therefore, it's possible that this is a downstream issue.

```
pip install ROPGadget
ROPgadget
```

- It may be necessary to open a new shell before the `ROPgadget` command is available in the path.
- I attempted to `pip install capstone` independently, but saw the same behavior.
- I was able to resolve this in my case by building capstone from source.

**Comment by Rot127** [comment] 2024-04-24 05:00
This is a duplicate of https://github.com/capstone-engine/capstone/issues/2301 and https://github.com/capstone-engine/capstone/issues/2066.
https://github.com/capstone-engine/capstone/issues/2301/https://github.com/capstone-engine/capstone/issues/2066 were fixed with https://github.com/capstone-engine/capstone/pull/2221 but not yet release as part of `v5.0.2`.

**Closed as completed by Rot127** 2024-04-24 05:00 UTC
Labels: duplicate, Python, MacOS
