### ISSUE TITLE
[PPC] Offset operand omitted if zero for memory accesses

### ISSUE THREAD

**Issue by nathanhjay** [aquynh/capstone#856] opened 2017-02-09 20:25 UTC
The second operand of some memory access intructions is omitted if it is zero, but this behavior isn't documented in the manual or supported by gas.

Bytes: `80 00 00 00`
Capstone Output: `lwz r0, (0)`
Accepted Output: `lwz r0, 0(0)`

**Comment by aquynh** [comment] 2017-02-11 09:29
i think the output of Capstone looks better, but yes maybe this is not really what other disassemblers handle this case.

besides GAS, any other PPC disassembler doing the same thing?

**Comment by nathanhjay** [comment] 2017-02-14 20:26
LLVM and GNU both produce the accepted version. The version that Capstone produces isn't currently suppported by gas.

**Comment by aquynh** [comment] 2017-02-19 13:28
fixed now, please confirm.

**Comment by parasyte** [comment] 2017-03-06 17:04
@aquynh This causes [`node-capstone`](https://github.com/parasyte/node-capstone) tests to fail on `lwz` instructions:

```
2) PPC : can be disassembled
   Error: --- expected
   +++ actual
   @@ -10,7 +10,7 @@
                0
            ],
            "mnemonic": "lwz",
   -        "op_str": "r1, 0"
   +        "op_str": "r1, 00"
        },
        {
            "arch": 4,
   @@ -23,7 +23,7 @@
                0
            ],
            "mnemonic": "lwz",
   -        "op_str": "r1, r31"
   +        "op_str": "r1, 0r31"
        },
        {
            "arch": 4,
       at Object.<anonymous> /Users/parasyte/projects/node-capstone/spec/PowerPC.spec.js:437:28

3) PPC : can be disassembled quickly
   Error: --- expected
   +++ actual
   @@ -3,13 +3,13 @@
            4096,
            4,
            "lwz",
   -        "r1, 0"
   +        "r1, 00"
        ],
        [
            4100,
            4,
            "lwz",
   -        "r1, r31"
   +        "r1, 0r31"
        ],
        [
            4104,
       at Object.<anonymous> /Users/parasyte/projects/node-capstone/spec/PowerPC.spec.js:444:28

4) PPC : can be disassembled with detail
   Error: --- expected
   +++ actual
   @@ -10,7 +10,7 @@
                0
            ],
            "mnemonic": "lwz",
   -        "op_str": "r1, 0",
   +        "op_str": "r1, 00",
            "detail": {
                "regs_read": [],
                "regs_write": [],
   @@ -46,7 +46,7 @@
                0
            ],
            "mnemonic": "lwz",
   -        "op_str": "r1, r31",
   +        "op_str": "r1, 0r31",
            "detail": {
                "regs_read": [],
                "regs_write": [],
       at Object.<anonymous> /Users/parasyte/projects/node-capstone/spec/PowerPC.spec.js:452:28
```

**Comment by aquynh** [comment] 2017-03-10 11:50
i cannot reproduce these issues. can you provide the hexcode?

**Comment by parasyte** [comment] 2017-03-10 16:52
@aquynh Hex code: https://github.com/parasyte/node-capstone/blob/0c972a01ef8c41060ee8e09f9820187e866f256c/spec/PowerPC.spec.js#L5-L9

**Comment by parasyte** [comment] 2017-03-10 16:56
I'll double-check to ensure it's not just a bug in the diff tool I'm using. The `op_str` should have parentheses around the base operand...

**Comment by parasyte** [comment] 2017-03-10 17:07
@aquynh False alarm :) It's definitely a bug outside of capstone. This looks good to me! 👍

**Comment by aquynh** [comment] 2017-03-10 17:14
thanks ;-)

**Closed by aquynh** 2017-03-10 17:14 UTC
