### ISSUE TITLE
Regressions for PPC in 'next' branch

### ISSUE THREAD

**Issue by ceeac** [aquynh/capstone#1468] opened 2019-04-30 07:40 UTC
- `cstool -d ppc64be "\x4b\xff\xf8\x00" 0x1000` returns `b 0x4000800` (should be `b 0x800`)
- Conditional branches have CS_OP_REG as first operand and not CS_OP_CRX
  Example: `cstool -d ppc64be "\x40\x94\x10\x00" 0x1000` (`bge cr5, 0x2000`)
  returns `operands[0].type: REG = r20`
- Conditional branches now are disassembled as `bt` or `bf` instead of `ble`, `beq` etc., is that intended?

**Comment by aquynh** [comment] 2019-05-07 08:09
fixed the B instruction in "next" branch now.

```
$ cstool -d ppc64be "\x4b\xff\xf8\x00" 1000 
1000  4b ff f8 00  b	0x800
	ID: 15 (b)
	op_count: 1
		operands[0].type: IMM = 0x800
	Groups: jump 
```

**Comment by radare** [comment] 2019-05-07 13:17
👍

**Comment by aquynh** [comment] 2019-05-08 06:00
> * `cstool -d ppc64be "\x4b\xff\xf8\x00" 0x1000` returns `b 0x4000800` (should be `b 0x800`)

fixed now, see above.

> * Conditional branches have CS_OP_REG as first operand and not CS_OP_CRX
>   Example: `cstool -d ppc64be "\x40\x94\x10\x00" 0x1000` (`bge cr5, 0x2000`)
>   returns `operands[0].type: REG = r20`

fixed now:

```
$ cstool -d ppc64be "\x40\x94\x10\x00" 0x1000 
1000  40 94 10 00  bf	cr5lt, 0x2000
	ID: 84 (bf)
	op_count: 2
		operands[0].type: REG = cr5lt
		operands[1].type: IMM = 0x2000
```

> * Conditional branches now are disassembled as `bt` or `bf` instead of `ble`, `beq` etc., is that intended?

yes.

**Comment by aquynh** [comment] 2019-05-08 06:03
since CS_OP_CRX is not really used now, i will remove it.

**Comment by ceeac** [comment] 2019-05-08 09:02
Found another regression. In `next`, the branch code member of `cs_ppc` is empty even for `bt` and `bf` instructions:

v4:
```bash
cstool -d ppc64be "\x40\x94\x10\x00" 0x1000
1000  40 94 10 00  bge	cr5, 0x2000
	op_count: 2
		operands[0].type: REG = cr5
		operands[1].type: IMM = 0x2000
	Branch code: 4
```

next:
```bash
cstool -d ppc64be "\x40\x94\x10\x00" 0x1000
1000  40 94 10 00  bf	cr5lt, 0x2000
	ID: 84 (bf)
	op_count: 2
		operands[0].type: REG = cr5lt
		operands[1].type: IMM = 0x2000
```

**Comment by aquynh** [comment] 2019-05-08 09:36
ok, will fix this soon.

**Comment by nwert** [comment] 2019-05-09 07:00
Ref. https://github.com/aquynh/capstone/commit/11206deb78b016a0532a24513550148a5df98d37#r33467875

**Comment by aquynh** [comment] 2019-05-09 16:58
@ceeac, i restored Bcc aliases now.

```
$ cstool -d ppc64be "\x40\x94\x10\x00" 0x1000
1000  40 94 10 00  bge	cr5, 0x2000
	ID: 92 (bge)
	op_count: 2
		operands[0].type: REG = cr5
		operands[1].type: IMM = 0x2000
	Branch code: 4
```

**Comment by nwert** [comment] 2019-05-10 23:16
I found another regression:

cstool output:
```
cstool -d ppc64be 4200FFF8 0x0101086C
101086c  42 00 ff f8  bdnz      0x1020864
        ID: 40 (bdnz)
        op_count: 1
                operands[0].type: IMM = 0x1020864
        Groups: jump
```

IDA output:
```
.text:01010864             loc_1010864:
.text:01010864 7C 89 19 2E                 stwx      r4, r9, r3
.text:01010868 39 29 00 04                 addi      r9, r9, 4
.text:0101086C 42 00 FF F8                 bdnz      loc_1010864  ; this is correct
.text:01010870 34 A5 FF FF                 addic.    r5, r5, -1
.text:01010874 40 82 FF E8                 bne       loc_101085C
.text:01010878 4E 80 00 20                 blr
```

**Comment by aquynh** [comment] 2019-05-11 02:19
fixed now.

```
$ cstool -d ppc64be 4200FFF8 0x0101086C
101086c  42 00 ff f8  bdnz	0x1010864
	ID: 40 (bdnz)
	op_count: 1
		operands[0].type: IMM = 0x1010864
	Groups: jump 
```

**Closed** 2019-06-03 14:59 UTC
